# <center>Outlier Detection and Handling Using Zscore

### Import Liabraries

In [2]:
import pandas as pd
import numpy as np
from scipy.stats import zscore
import warnings
warnings.filterwarnings("ignore")

### Load DataSet

In [3]:
df = pd.read_csv("StudentsPerformance.csv")
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [4]:
df.tail()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [5]:
df.shape

(1000, 8)

In [6]:
df.size

8000

### Checking Unique values of Simple Columns

In [7]:
for col in df.columns:

 if df[col].nunique() <= 10:

     print(f"\nColumn: {col}")
     print(df[col].unique())

Column: gender
['female' 'male']

Column: race/ethnicity
['group B' 'group C' 'group A' 'group D' 'group E']

Column: parental level of education
["bachelor's degree" 'some college' "master's degree" "associate's degree"
 'high school' 'some high school']

Column: lunch
['standard' 'free/reduced']

Column: test preparation course
['none' 'completed']

### Dataset Information

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB

In [9]:
df.describe()

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

### Checking Missing Values

In [10]:
df.isnull().sum()

gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64

### Remove Duplicates

In [11]:
print(df.duplicated().sum())

0

### Feature Selection

In [12]:
df.drop(columns=["race/ethnicity"], inplace=True)
df.head()

,gender,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,bachelor's degree,standard,none,72,72,74
1,female,some college,standard,completed,69,90,88
2,female,master's degree,standard,none,90,95,93
3,male,associate's degree,free/reduced,none,47,57,44
4,male,some college,standard,none,76,78,75

### Outlier Detection

In [13]:
columns = df.select_dtypes(include = "number").columns
# Calculate Z-score
z_scores = np.abs(zscore(df[columns]))
# Identify outliers
outlier_counts = (z_scores > 3).sum(axis=0)
# Print column name and number of outliers
for i in range(len(columns)):
 print(columns[i], ":", outlier_counts[i], "outliers")

math score : 4 outliers
reading score : 4 outliers
writing score : 4 outliers

### The Actual Outlier Values

In [14]:
for column in columns:

 z = np.abs(zscore(df[column]))

 print("\n", column)
 print(df[column][z > 3])

 math score
17     18
59      0
787    19
980     8
Name: math score, dtype: int64

 reading score
59     17
327    23
596    24
980    24
Name: reading score, dtype: int64

 writing score
59     10
76     22
327    19
596    15
Name: writing score, dtype: int64

### Outlier Handling

In [15]:
outlier_cols = ["math score","reading score","writing score"]

In [16]:
df_clean = df.copy()
for column in outlier_cols:

 z = np.abs(zscore(df_clean[column]))

 median = df_clean[column].median()

 df_clean.loc[z > 3, column] = median

In [17]:
print("Original shape:", df.shape)
print("Cleaned shape:", df_clean.shape)

Original shape: (1000, 7)
Cleaned shape: (1000, 7)

### Outliers Removal

In [18]:
df_clean = df.copy()
for column in outlier_cols:
     z = np.abs(zscore(df_clean[column]))
     df_clean = df_clean[z <= 3]
print("Original shape:", df.shape)
print("Cleaned shape:", df_clean.shape)

Original shape: (1000, 7)
Cleaned shape: (993, 7)